# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

   language: 
     - swift
   osx_image: xcode10.1
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
env:
  - XCWORKSPACE="Example/myLibrary.xcworkspace"

install:
  - bundle install
script:
  - fastlane tests
